# Docker Compose Definitions for local Developer Environment
version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: appserive_zookeeper
    ports:
      - "2181:2181"
  kafka:
    restart: always
    image: wurstmeister/kafka:latest
    container_name: appserive_kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092,INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
    expose:
      - 9093
  postgres:
    image: postgres:10
    restart: always
    container_name: appserive_postgres
    environment:
      POSTGRES_USER: appservice
      POSTGRES_PASSWORD: appservice
      POSTGRES_DATABASE: appservice
    ports:
      - 5432:5432
  producer:
    restart: always
    container_name: appserive_producer
    build:
       context: appservice/producer
       dockerfile: Dockerfile
    environment:
      DOCKER: 1
    volumes:
      - ./appservice:/appservice
    ports:
      - 8000:8000
    depends_on:
      - kafka
      - postgres
      - zookeeper
      - redis
    entrypoint: 'python3 -u /appservice/producer/manage.py'
  consumer:
    restart: always
    container_name: appserive_consumer
    build:
       context: appservice/consumer
       dockerfile: Dockerfile
    environment:
      DOCKER: 1
      DATA_STORAGE: POSTGRES
      OFFSET_STORAGE: REDIS
    volumes:
      - ./appservice:/appservice
    ports:
      - 5001:5001
    depends_on:
      - kafka
      - postgres
      - zookeeper
      - redis
      - cassandra
    entrypoint: 'python3 -u /appservice/consumer/manage.py'
  redis:
    image: "redis"
    container_name: appserive_redis
    volumes:
    - ./redis:/var/lib/redis/data
    ports:
    - 6379
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "9042:9042"
    restart: always